### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by BrunoNogu** [patagonaa/homeassistant-unifi-led#3]
Hello!

This is exactly what I'm looking for but I have no idea on how to install it :(

I'm currently running hass.io image and already performed the command git clone but I don't know about the next step.
Is it possible to install it as an addon?

Thanks!

**Comment by patagonaa** [comment]
I'm afraid this project doesn't really work with current Unifi firmware if I remember correctly (last time I've checked the LED state gets overwritten regularly by the setting configured in the Unifi controller).
This project was done more as proof of concept instead of something reliable for anyone to use, so this has to be installed manually via docker / docker-compose.

Thank you for your interest though.

**Comment by patagonaa** [comment]
however, if you wanna try (and have docker and docker-compose installed already) the full installation steps should be:
```
git clone --recurse-submodules https://github.com/patagonaa/homeassistant-unifi-led.git
cd homeassistant-unifi-led
cp src/HomeAssistantUnifiLed/config.example.json src/HomeAssistantUnifiLed/config.json
```
then edit `src/HomeAssistantUnifiLed/config.json` to add your MQTT server and access points (with SSH credentials).
then start the app using
```
docker-compose up -d --build
```
and things _should_ be up and running (logs can be checked via `docker-compose logs -f`)

**Comment by patagonaa** [comment]
Issue with current firmware (#2) is fixed now btw

**Comment by BrunoNogu** [comment]
Hi @patagonaa 

Thank you very much for your quick reply :)

I will try to install it

Thanks!
